# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpcEcho_pb2 as rpcEcho__pb2


class EchoImageServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ProcessImage = channel.unary_unary(
        '/EchoImageService/ProcessImage',
        request_serializer=rpcEcho__pb2.EchoImage.SerializeToString,
        response_deserializer=rpcEcho__pb2.Empty.FromString,
        )


class EchoImageServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ProcessImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EchoImageServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ProcessImage': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessImage,
          request_deserializer=rpcEcho__pb2.EchoImage.FromString,
          response_serializer=rpcEcho__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'EchoImageService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
